language: ruby

#services:
#  - docker

#env:
#  global:
#    - TF_LOG=DEBUG

before_install:
#  - docker pull hashicorp/terraform:0.12.9
  - curl -fSL "https://releases.hashicorp.com/terraform/0.12.9/terraform_0.12.9_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform

jobs:
  include:
    - stage: plan
      if:
        - branch != master
      script:
        - terraform init
        - terraform validate
        - terraform plan
        
    - stage: apply
      if:
        - branch = master
      script:
        - terraform init
        - terraform apply -auto-approve
        
    - stage: destory
      if:
        - branch = master
      script:
        - terraform init
        - terraform destroy -auto-approve

