services:
  - docker

#env:
#  global:
#    - TF_LOG=DEBUG

before_install:
#  - docker pull hashicorp/terraform:light
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform

script:
  - terraform init
  - terraform plan
